language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/regnumber_tests

node_js:  
  - "12"

before_script:
  - psql -c 'create database  regnumber_tests;' -U postgres
  - psql -U postgres -d my_products_tests -a -f tables.sql

services:
  - postgresql